Participants States
buerokratt/POC.CentOps pull request #50
Opened 2022-06-22 07:26 UTC by shelabd

Added the expected participants states for each scenario of the CRUD operations for CentOps

2022-06-22 08:12 UTC, turnerrainer approved these changes
B`eu`rokratt to B`ue`rokratt throughout the document but not a blocker

2022-06-22 08:12 UTC, turnerrainer commented on docs/Participants States.md
> +This document defines the states of all participants of the Beurokratt network. The states will be stored, updated and removed as part of the CentOps Admin operations to ensure that the overall state
```suggestion
This document defines the states of all participants of the Buerokratt network. The states will be stored, updated and removed as part of the CentOps Admin operations to ensure that the overall state of the network is kept up to date and concurrent with the literal state of the institutions participating in the Buerokratt network.  

```

2022-06-22 08:12 UTC, turnerrainer commented on docs/Participants States.md
> +Is any component operating in the Beurokratt network. These are: Bots, Classifier and DMRs
```suggestion
Is any component operating in the Buerokratt network. These are: Bots, Classifier and DMRs

```

2022-06-22 08:12 UTC, turnerrainer commented on docs/Participants States.md
> +| Institution requests to be registered into the Beurokratt network, the institution gets added to the routing table: Institution | Institution: Offline           |
```suggestion
| Institution requests to be registered into the Buerokratt network, the institution gets added to the routing table: Institution | Institution: Offline           |

```

2022-06-22 08:12 UTC, turnerrainer commented on docs/Participants States.md
> +| Request for institution to be removed from the Beurokratt Network | Institution: Revoked           |
```suggestion
| Request for institution to be removed from the Buerokratt Network | Institution: Revoked           |

```

2022-06-22 08:12 UTC, turnerrainer commented on docs/Participants States.md
> +| Request for institution bot to be deleted from the Beurokratt Network | Institution: Deleted           |
```suggestion
| Request for institution bot to be deleted from the Buerokratt Network | Institution: Deleted           |

```

2022-06-22 09:59 UTC, decodingahmed requested changes

2022-06-22 09:59 UTC, decodingahmed commented on docs/Participants States.md
> +This document defines the states of all participants of the Buerokratt network. The states will be stored, updated and removed as part of the CentOps Admin operations to ensure that the overall state
This might be quite pedantic but the CentOps Public API can also update the state of the participant.

2022-06-22 09:59 UTC, decodingahmed commented on docs/Participants States.md
> +| Request for institution bot to be deleted from the Buerokratt Network | Institution: Deleted           |
Would the `Deleted` state simply be that the participant is entirely removed from the database so they don't exist?

2022-06-22 09:59 UTC, decodingahmed commented on docs/Participants States.md
> +| Classifier to be deleted from the network      | Classifier: Deleted           |
Same as above regarding `Deleted` state

2022-06-22 09:59 UTC, decodingahmed commented on docs/Participants States.md
> +| DMR to be deleted from the network      | DMR: Deleted           |
Here too

2022-06-22 09:59 UTC, decodingahmed commented on docs/Participants States.md
> +| Scenario                                                     | State                          |
Do you think there's value in including whether an admin or other participants are allowed to switch between these states. For example, admins and participants can switch between Offline and Online but only admin can revoke or delete.

2022-06-22 11:20 UTC, turnerrainer commented on docs/Participants States.md
> +| Request for institution bot to be deleted from the Buerokratt Network | Institution: Deleted           |
Can't do that. We don't use `DELETE` or `UPDATE` at all.

2022-06-22 11:22 UTC, turnerrainer commented on docs/Participants States.md
> +| Scenario                                                     | State                          |
I see value in participants not being able to revoke their membership while admin having the capabilities to do that. Don't you, @decodingahmed ?

2022-06-28 08:43 UTC, joonasroosalung commented on docs/Participants States.md
> +
Newlines break the table here

2022-06-28 08:46 UTC, shelabd commented on docs/Participants States.md
> +
Thank you!

2022-06-30 13:27 UTC, decodingahmed approved these changes

2022-07-04 10:07 UTC, guypritchard approved these changes

2022-07-04 13:16 UTC, merged