Feature/38 participants list request
buerokratt/POC.CentOps pull request #57
Opened 2022-06-28 13:08 UTC by joonasroosalung

2022-06-28 14:51 UTC, guypritchard requested changes
Can we have some tests for this new functionality too?

2022-06-28 14:51 UTC, guypritchard commented on src/CentOps.Api/Controllers/PublicInstitutionController.cs
> +        public async Task<ActionResult<IEnumerable<ParticipantResponseModel>>> Get(string id)
I'm not 100% sure about this - this looks like we're asking for a participant of a specific id. 

I'm wondering if this wants to be

/public/institutions/{id}/participants?  We'd still need /public/insititutions/{id} too possibly?

2022-06-28 17:35 UTC, yahya130 commented on src/CentOps.Api/Controllers/PublicParticipantController.cs
> +        public async Task<ActionResult<IEnumerable<ParticipantResponseModel>>> Get(string id)
Just a question, are we returning 1 single participant here? if so, we are returning it as a collection, perhaps this would be more suitable? please correct me if I have misunderstood
```suggestion
        public async Task<ActionResult<ParticipantResponseModel>> Get(string id)
```

2022-06-29 07:10 UTC, joonasroosalung commented on src/CentOps.Api/Controllers/PublicInstitutionController.cs
> +        public async Task<ActionResult<IEnumerable<ParticipantResponseModel>>> Get(string id)
I was uncertain here, but this is how much I understood the AC here. In my mind this covers "Return participants of specific institutions". Since there was no "Return specific institution" I felt like this could be covered by that. Of course it might make much more sense if institutions/{id} returned just an institution like on the "admin" side.

Anyway long ramble, but I think you're right.

2022-06-29 07:13 UTC, joonasroosalung commented on src/CentOps.Api/Controllers/PublicParticipantController.cs
> +        public async Task<ActionResult<IEnumerable<ParticipantResponseModel>>> Get(string id)
This one I have to admin I simply copied from ParticipantController. But it doesn't return a collection in either case, so I will adjust both of them to your recommendation, thanks!

2022-06-29 08:02 UTC, yahya130 approved these changes

2022-06-29 14:00 UTC, guypritchard approved these changes
Much better!  Thanks!

2022-06-29 14:02 UTC, merged