Implement Api Key based authentication
buerokratt/POC.CentOps pull request #58
Opened 2022-06-28 18:15 UTC by decodingahmed

2022-06-29 15:00 UTC, yahya130 approved these changes

2022-06-29 15:54 UTC, guypritchard requested changes
Some minor things - is it worth a chat?

2022-06-29 15:54 UTC, guypritchard commented on src/CentOps.Api/Services/InMemoryStore.cs
> +    public sealed partial class InMemoryStore : IParticipantStore, IInstitutionStore
We probably need a task to Implement the Cosmos version of this storage layer - or @adelechurchill will be picking up extra work in her task here.

2022-06-29 15:54 UTC, guypritchard commented on src/CentOps.Api/Services/InMemoryApiUserStore.cs
> +            ApiKey = "iamadmin",
Shouldn't this come from secret configuration rather than being baked in - even for this early implementation?

2022-06-29 15:54 UTC, guypritchard commented on src/CentOps.Api/Services/ModelStore/Models/ApiUserDto.cs
> +        public string? Id { get; set; }
Thinking about Participant -> API Key mapping - do you see this being a separate field or would the ids match or something?

2022-06-29 15:54 UTC, guypritchard commented on src/CentOps.Api/Controllers/AdminInstitutionController.cs
> +        public AdminInstitutionController(IInstitutionStore store, IMapper mapper)
Yes - good shout!

2022-06-30 12:08 UTC, martinkearn approved these changes
Looking good. All comments are minor so feel free to resolve them without addressing them

2022-06-30 12:08 UTC, martinkearn commented on src/CentOps.Api.Authentication/ApiKeyAuthenticationHandler.cs
> +                return AuthenticateResult.Fail($"The '{Options.ApiKeyHeaderName}' header does not contain a value.");
Could this string be in a constants file? Not sure if you can still do token replacement if it is but one to look at? Same applies to others too

2022-06-30 12:08 UTC, martinkearn commented on src/CentOps.Api.Authentication/CentOps.Api.Authentication.csproj
> +    <Nullable>enable</Nullable>
`Nullable` has been disabled on most of the other Burokrat projects so it could be disabled here too if necessary

2022-06-30 12:08 UTC, martinkearn commented on src/CentOps.Api.Authentication/CentOps.Api.Authentication.csproj
> +
Does this project have all the same code styling settings as the other C# projects? If not, can we add them?

2022-06-30 12:08 UTC, martinkearn commented on src/CentOps.Api/Extensions/ServiceCollectionExtensions.cs
> +                        .RequireClaim("isAdmin", "TRUE");
I don't know if this is possible, but could this be `Boolean.TrueString` instead?

2022-06-30 12:08 UTC, martinkearn commented on src/CentOps.UnitTests/Authentication/ApiKeyAuthenticationHandlerTests.cs
> +            _ = failure.Message.Should().Be("The 'X-Api-Key' header does not contain a value.");
Could/should this be a `const` shared between project and test? Same applies to all strings

2022-06-30 12:08 UTC, martinkearn commented on src/CentOps.UnitTests/Authentication/Extensions/AuthenticationBuilderExtensionsTests.cs
> +        //[Theory]
Commented code should be removed

2022-07-04 18:14 UTC, decodingahmed commented on src/CentOps.Api/Services/ModelStore/Models/ApiUserDto.cs
> +        public string? Id { get; set; }
The `ApiUserDto` model is no longer a thing as the ApiKey and IsAdmin properties have been moved to Participant and Institution DTOs

2022-07-04 18:14 UTC, decodingahmed commented on src/CentOps.Api/Services/InMemoryApiUserStore.cs
> +            ApiKey = "iamadmin",
I've removed this now

2022-07-04 18:14 UTC, decodingahmed commented on src/CentOps.Api/Extensions/ServiceCollectionExtensions.cs
> +                        .RequireClaim("isAdmin", "TRUE");
Done, thanks!

2022-07-04 18:14 UTC, decodingahmed commented on src/CentOps.Api/Services/InMemoryStore.cs
> +    public sealed partial class InMemoryStore : IParticipantStore, IInstitutionStore
This is now implemented.

2022-07-04 18:14 UTC, decodingahmed commented on src/CentOps.Api.Authentication/ApiKeyAuthenticationHandler.cs
> +                return AuthenticateResult.Fail($"The '{Options.ApiKeyHeaderName}' header does not contain a value.");
We won't be able to do string interpolation if we turn this into a constant.  I would consider making a string helper but since it is only 1 instance, it won't be worth it.

2022-07-04 18:14 UTC, decodingahmed commented on src/CentOps.Api.Authentication/CentOps.Api.Authentication.csproj
> +    <Nullable>enable</Nullable>
The projects in CentOps repo have nullable enabled so I'm following that. Plus, changing this now would cause additional code changes. Sorry, I won't apply this.

2022-07-04 18:14 UTC, decodingahmed commented on src/CentOps.UnitTests/Authentication/ApiKeyAuthenticationHandlerTests.cs
> +            _ = failure.Message.Should().Be("The 'X-Api-Key' header does not contain a value.");
If this was real code I would agree with you but I see greater value in seeing the error messages in line. Besides, they are only a single instance of the string. Sorry, I won't be actioning this.

2022-07-04 18:14 UTC, decodingahmed commented on src/CentOps.UnitTests/Authentication/Extensions/AuthenticationBuilderExtensionsTests.cs
> +        //[Theory]
Fair point, this was WIP but the test was near impossible to write. I've removed the comment code. Thank you!

2022-07-04 18:14 UTC, decodingahmed commented on src/CentOps.Api.Authentication/CentOps.Api.Authentication.csproj
> +
I've added these in now, thanks!  To be honest, the code styling stuff kicked in automatically because this project was referenced in the main project, that's why there aren't any styling changes.

2022-07-06 07:32 UTC, guypritchard approved these changes

2022-07-06 07:32 UTC, guypritchard commented on .github/workflows/ci-pullrequest-main.yml
> +      run: dotnet stryker --project CentOps.Api.csproj && dotnet stryker --project CentOps.Api.Authentication.csproj
Does this cope with one of the projects not having enough coverage? e.g. are the return values for both respected when run like this?

2022-07-06 08:27 UTC, decodingahmed commented on .github/workflows/ci-pullrequest-main.yml
> +      run: dotnet stryker --project CentOps.Api.csproj && dotnet stryker --project CentOps.Api.Authentication.csproj
I've checked this by running it locally. Yes it does, it works this out and takes it into account when working out coverage and mutation.

2022-07-06 08:27 UTC, merged