Update Dockerfile to include the authentication project
buerokratt/POC.CentOps pull request #75
Opened 2022-07-08 15:42 UTC by martinkearn

This PR is a simple fix to make sure that the authentication project is included in the Docker image for this repo.

There is no associated issue (it was not worth creating one)

2022-07-08 15:45 UTC, yahya130 approved these changes

2022-07-08 15:50 UTC, guypritchard approved these changes

2022-07-08 16:03 UTC, martinkearn commented
Just adding a comment to hold this PR ... we may not need it after all

2022-07-08 16:06 UTC, guypritchard requested changes
Lets see if we need this at all...

2022-07-11 08:10 UTC, martinkearn commented
We're abandoning this PR as it is no longer needed

2022-07-11 08:10 UTC, closed without merging