enabling update participant feature
buerokratt/POC.CentOps pull request #88
Opened 2022-07-22 13:28 UTC by yahya130

This PR allows for participant states to be updated

2022-07-22 15:45 UTC, martinkearn approved these changes

2022-07-22 15:45 UTC, martinkearn commented on .github/workflows/ci-pullrequest-main.yml
> +      run: docker image build -f src/CentOps.Api/Dockerfile ./src
This does not seem to be a deliberate change?

2022-07-22 15:45 UTC, martinkearn commented on src/CentOps.Api/Controllers/PublicParticipantController.cs
> +                return Ok(_mapper.Map<ParticipantStateReponseModel>(response));
super nit: Just from a readability perspective, I always favour having a var for the thing you are returning separate from the return statement itself. I find it easier to read that way, could just be me though, feel free to ignore.
```suggestion
                var result = _mapper.Map<ParticipantStateReponseModel>(response);
                return Ok(result);
```

2022-07-22 15:45 UTC, martinkearn commented on src/CentOps.Api/Controllers/PublicParticipantController.cs
> +            catch (Exception ex) when (ex is ModelNotFoundException<ParticipantDto> or ArgumentException or ArgumentNullException)
Would `when (ex is ModelNotFoundException<ParticipantDto>` ever get hit because you are checking for that on line 62?

2022-07-22 15:45 UTC, martinkearn commented on src/CentOps.Api/Dockerfile
> -
Just double checking this is deliberate? If it is, please ignore

2022-07-22 16:00 UTC, yahya130 commented on src/CentOps.Api/Controllers/PublicParticipantController.cs
> +                return Ok(_mapper.Map<ParticipantStateReponseModel>(response));
Agreed just a short cut this, but readability would be a reason to commit this change

2022-07-22 16:01 UTC, yahya130 commented on src/CentOps.Api/Controllers/PublicParticipantController.cs
> +            catch (Exception ex) when (ex is ModelNotFoundException<ParticipantDto> or ArgumentException or ArgumentNullException)
Good spot, will update

2022-07-22 16:03 UTC, yahya130 commented on .github/workflows/ci-pullrequest-main.yml
> +      run: docker image build -f src/CentOps.Api/Dockerfile ./src
Accidental, I will leave remove this from the PR

2022-07-22 16:10 UTC, guypritchard requested changes

2022-07-22 16:10 UTC, guypritchard commented on src/CentOps.Api/Controllers/PublicParticipantController.cs
> +                var response = await _store.UpdateState(id, newState).ConfigureAwait(false);
I think on the public API we need to look at the API key we've been given here too - a participant shouldn't be able to alter the state of another participant just because they have the ID.  Or is this somewhere else in the code I'm not seeing?
If the Id and the Id of the participant doesn't match we shouldn't proceed.  Have a look at the code which adds the participant Id.

Note - this pushes on there always being unique API keys... The current functionality allows duplicates - but as you can probably guess this means the code may misidentify the participant.

2022-07-22 16:20 UTC, guypritchard commented on src/CentOps.Api/Models/ParticipantResponseModel.cs
> +        public ParticipantState State { get; set; }
Do we need a new property for this?  Could we not just add the states here to ParticipantStatus or does this truly need to be something else?

2022-07-22 16:29 UTC, decodingahmed requested changes

2022-07-22 16:29 UTC, decodingahmed commented on src/CentOps.Api/Program.cs
> +
supernit: remove empty line please
```suggestion
```

2022-07-22 16:29 UTC, decodingahmed commented on src/CentOps.Api/Services/CosmosDbService.cs
> +            var validStateChanges = new List<ParticipantState>() { ParticipantState.Online, ParticipantState.Offline };
Could you make this list a static variable at the top of the class please?  This line will recreate this list for every request so lets reduce those unnecessary allocations.

2022-07-22 16:29 UTC, decodingahmed commented on src/CentOps.Api/Services/CosmosDbService.cs
> +            var response = await store.Update(participant).ConfigureAwait(false);
There is a way to just update a property in Cosmos. I'll call to walk through how we can do that. It will save you from having to fetch then update the whole object.

2022-07-22 16:29 UTC, decodingahmed commented on src/CentOps.Api/Models/ParticipantState.cs
> +    public enum ParticipantState
Please correct me if this is wrong, but I think this `ParticipantState` and the existing `ParticipantStatus` enums are trying to do the same thing @guypritchard, what do you think?

2022-07-22 16:31 UTC, guypritchard commented on src/CentOps.Api/Models/ParticipantState.cs
> +    public enum ParticipantState
I added a comment about this - I think so, I think we could get away with adding these states to the existing enum.

2022-07-22 19:13 UTC, yahya130 commented on src/CentOps.Api/Controllers/PublicParticipantController.cs
> +                var response = await _store.UpdateState(id, newState).ConfigureAwait(false);
I implemented this at first, but I realized and you mentioned on the teams chat too, that this is handled by the authentication logic and would be good to capture any further functionality there

2022-07-23 00:05 UTC, yahya130 commented on src/CentOps.Api/Services/CosmosDbService.cs
> +            var response = await store.Update(participant).ConfigureAwait(false);
Agreed, I had a little trouble last minute when the test failed trying to mock up (https://github.com/buerokratt/CentOps/pull/88/commits/b9375e6e8edc80a40b7aa8451a645a489feadc4f#diff-70e24f7e44ff7fe71ab6cd266d2f09e6c034f8d4ce99c4c186067be07e54b59c) the cosmosdb patch method so I reverted back to the update method

2022-07-23 00:13 UTC, yahya130 commented on src/CentOps.Api/Models/ParticipantState.cs
> +    public enum ParticipantState
I was not sure whether ParticipantStatus was being used in other areas of the code, but to me having read this doc (https://github.com/buerokratt/CentOps/blob/main/docs/Participants%20States.md), there were some grey areas for example, offline/online vs active/disabled, also feel based off that doc and other areas of the project the naming of 'ParticipantState' over 'ParticipantStatus' seemed more natural, so for me perhaps updating the naming to 'ParticipantState' might be up for consideration, but of course happy with 'ParticipantStatus' if that is the preference :)

2022-07-24 21:06 UTC, yahya130 commented on src/CentOps.Api/Controllers/PublicParticipantController.cs
> +        [HttpPut("my/state")]
Just a question, is this the most restful way to do this in terms of the new path? I know the definition of restful is a very open topic, but would be good to understand :) also I noticed the id param is removed, how is the id passed into the request now?

2022-07-25 17:09 UTC, decodingahmed commented on src/CentOps.Api/Controllers/PublicParticipantController.cs
> +        [HttpPut("my/state")]
In terms of RESTful pattern, here's the thinking:
This is the complete path of this endpoint: `/public/participants/my/state`

`/public/participants` - pluralised resource path
`/my` - this is equivalent to having an `id` but we specify "my" so it still fits the standard pattern
`/state` - is allowed as a subpath (aka a micro-endpoint)

Regarding the removed `id` param, at the moment none of the participants know their own ID so asking them to provide it would mean that we would need to make a change elsewhere.

Secondly, we are able to identify them using their API key so when they call CentOps, it pulls their record from the DB to validate that the API key exists. Other information about the participant, like the `id`, is loaded up in the request from within authentication (see `ApiUserClaimsProvider.cs`)

Hope all that made sense. Please ping me if you want to talk more about this dude. Thanks for the comment @yahya130

2022-07-25 17:11 UTC, decodingahmed commented on src/CentOps.Api/Models/ParticipantState.cs
> +    public enum ParticipantState
@guypritchard and I agree with you but I think for now we will stick with "state" because migrating existing properties and records in CentOps will become a pain in the backside.

2022-07-25 17:35 UTC, decodingahmed approved these changes

2022-07-25 17:48 UTC, guypritchard approved these changes

2022-07-25 17:48 UTC, guypritchard commented on src/CentOps.Api/Services/CosmosDbService.cs
> +                ("@status", ParticipantStatusDto.Deleted));
Thinking out loud:  Should this only return an API key for Active participants?  (e.g. not Delete OR Disabled?)

2022-07-25 17:48 UTC, guypritchard commented on src/CentOps.Api/Services/ApiUserClaimsProvider.cs
> +                    new Claim("pk", user.PartitionKey!),
Is putting the partition key in a claim a bit weird?  Is this to make querying later on easier?

2022-07-25 17:48 UTC, guypritchard commented on src/CentOps.Api/Services/CosmosDbService.cs
> +        public async Task<ParticipantDto> UpdateState(string id, string partitionKey, ParticipantStatusDto newStatus)
Can we not deduce the partition key here?  Or is there something we can't infer?

2022-07-26 09:14 UTC, guypritchard commented on src/CentOps.Api/Services/CosmosDbService.cs
> +                ("@status", ParticipantStatusDto.Deleted));
We think Disabled actually means active and offline.  Keys should still be valid in this situation.

2022-07-26 09:19 UTC, guypritchard commented on src/CentOps.Api/Services/CosmosDbService.cs
> +                ("@status", ParticipantStatusDto.Deleted));
I think we're going to no longer expose partition keys externally.

2022-07-26 09:20 UTC, guypritchard commented on src/CentOps.Api/Services/ApiUserClaimsProvider.cs
> +                    new Claim("pk", user.PartitionKey!),
We don't think we'll need this anymore.

2022-07-26 09:21 UTC, guypritchard commented on src/CentOps.Api/Services/CosmosDbService.cs
> +        public async Task<ParticipantDto> UpdateState(string id, string partitionKey, ParticipantStatusDto newStatus)
We're no longer going to expose partition keys externally

2022-07-26 09:33 UTC, decodingahmed commented on src/CentOps.Api/Services/ApiUserClaimsProvider.cs
> +                    new Claim("pk", user.PartitionKey!),
PartitionKey claim has been removed

2022-07-26 09:34 UTC, decodingahmed commented on src/CentOps.Api/Services/CosmosDbService.cs
> +        public async Task<ParticipantDto> UpdateState(string id, string partitionKey, ParticipantStatusDto newStatus)
This method no longer takes the `partitionKey` param.

2022-07-26 09:46 UTC, merged