Adding CORS in for CentOps APIS
buerokratt/POC.CentOps pull request #91
Opened 2022-07-25 17:31 UTC by guypritchard

2022-07-26 13:43 UTC, martinkearn approved these changes

2022-07-26 13:43 UTC, martinkearn commented on src/CentOps.Api/Extensions/ServiceCollectionExtensions.cs
> +                            corsConfig?.AllowedOrigins != null && corsConfig.AllowedOrigins.Any()
Would this be more readable if the value of this was worked out in a separate var which is passed in here? I'm finding it a bit hard to read in-line.

2022-07-26 14:22 UTC, decodingahmed requested changes

2022-07-26 14:22 UTC, decodingahmed commented on src/CentOps.Api/Extensions/ServiceCollectionExtensions.cs
> +                            : new string[] { "*" })
1. If `AllowedOrigins` is null/empty, I think we should fall back to the actual host instead of `*` otherwise we might start accepting requests from anywhere, right?  Sorry if I'm misunderstanding this.

2. Also, could you please move the `AllowedOrigin` logic outside of the AddCors block so it is a little easier to read.

2022-07-26 14:22 UTC, decodingahmed commented on src/CentOps.Api/appsettings.Development.json
> +    "AllowedOrigins": [ "*" ]
I think this should be the host

2022-07-26 15:05 UTC, guypritchard commented on src/CentOps.Api/Extensions/ServiceCollectionExtensions.cs
> +                            corsConfig?.AllowedOrigins != null && corsConfig.AllowedOrigins.Any()
Yep - will do.

2022-07-26 15:44 UTC, guypritchard commented on src/CentOps.Api/Extensions/ServiceCollectionExtensions.cs
> +                            : new string[] { "*" })
We spoke about this:

Summary - having some sort of a default if the configuration specified is useful hear as it means the service will start.  The dumb thing was allowing * domains in that instance.  We agreed to specify `localhost` as a fallback.  It will allow the service to start without config - but it will allow integration tests to pass, but a browser will complain bitterly, but in a way which Web Developers will understand if they call this API from the 'wrong' domain.

2022-07-26 15:45 UTC, guypritchard commented on src/CentOps.Api/appsettings.Development.json
> +    "AllowedOrigins": [ "*" ]
See above comment - we're falling back to `localhost` a valid but better default for an unconfigured state.

2022-07-26 16:42 UTC, decodingahmed approved these changes

2022-07-26 16:42 UTC, decodingahmed commented on src/CentOps.Api/appsettings.Development.json
> +    "AllowedOrigins": [ "*" ]
I think this may have been missed. Could you change the `*` to `locahost` please?

2022-07-26 16:42 UTC, decodingahmed commented on src/CentOps.Api/appsettings.json
> +    "AllowedOrigins":  ["*"]
I think this may have been missed. Could you change the `*` to `locahost` please?
```suggestion
    "AllowedOrigins":  ["localhost"]
```

2022-07-27 08:30 UTC, guypritchard commented on src/CentOps.Api/appsettings.Development.json
> +    "AllowedOrigins": [ "*" ]
This is really only development configuration - I'm only going to see this when running locally.  I've changed for consistency with other configuration - it certainly won't hurt at this stage.

2022-07-27 08:40 UTC, merged